/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAutocomplete: typeof import('./src/components/common/AppAutocomplete.vue')['default']
    AppAvatar: typeof import('./src/components/common/AppAvatar.vue')['default']
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppConfirmDialog: typeof import('./src/components/common/AppConfirmDialog.vue')['default']
    AppDataTable: typeof import('./src/components/common/AppDataTable.vue')['default']
    AppDatePicker: typeof import('./src/components/common/AppDatePicker.vue')['default']
    AppDialog: typeof import('./src/components/common/AppDialog.vue')['default']
    AppImageCropper: typeof import('./src/components/common/AppImageCropper.vue')['default']
    AppInfiniteScroll: typeof import('./src/components/common/AppInfiniteScroll.vue')['default']
    AppInput: typeof import('./src/components/common/AppInput.vue')['default']
    AppPageHeader: typeof import('./src/components/common/AppPageHeader.vue')['default']
    AppPasswordInput: typeof import('./src/components/common/AppPasswordInput.vue')['default']
    AppPhone: typeof import('./src/components/common/AppPhone.vue')['default']
    AppSkeleton: typeof import('./src/components/common/AppSkeleton.vue')['default']
    AppSwitch: typeof import('./src/components/common/AppSwitch.vue')['default']
    AppTextarea: typeof import('./src/components/common/AppTextarea.vue')['default']
    Calculator: typeof import('./src/components/tools/Calculator.vue')['default']
    CanView: typeof import('./src/components/common/CanView.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@ui/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@ui/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@ui/components/cards/CardStatisticsWithImages.vue')['default']
    CompanySwitchDialog: typeof import('./src/components/common/CompanySwitchDialog.vue')['default']
    DefaultAutocomplete: typeof import('./src/@ui/components/DefaultAutocomplete.vue')['default']
    DefaultField: typeof import('./src/@ui/components/DefaultField.vue')['default']
    DefaultSelect: typeof import('./src/@ui/components/DefaultSelect.vue')['default']
    DefaultTextarea: typeof import('./src/@ui/components/DefaultTextarea.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorMessage: typeof import('./src/components/common/ErrorMessage.vue')['default']
    FinancialCustomerCard: typeof import('./src/components/common/FinancialCustomerCard.vue')['default']
    FormActions: typeof import('./src/components/forms/FormActions.vue')['default']
    FormField: typeof import('./src/components/forms/FormField.vue')['default']
    FormSection: typeof import('./src/components/forms/FormSection.vue')['default']
    InstallmentCalc: typeof import('./src/components/tools/InstallmentCalc.vue')['default']
    InventoryForm: typeof import('./src/components/forms/InventoryForm.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MediaGallery: typeof import('./src/components/common/MediaGallery.vue')['default']
    MoreBtn: typeof import('./src/@ui/components/MoreBtn.vue')['default']
    NoteForm: typeof import('./src/components/forms/NoteForm.vue')['default']
    PagePlaceholder: typeof import('./src/components/common/PagePlaceholder.vue')['default']
    PaymentForm: typeof import('./src/components/forms/PaymentForm.vue')['default']
    PrintTemplate: typeof import('./src/components/common/PrintTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceForm: typeof import('./src/components/forms/ServiceForm.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StatsCard: typeof import('./src/components/common/StatsCard.vue')['default']
    ThemeSwitcher: typeof import('./src/@ui/components/ThemeSwitcher.vue')['default']
  }
}
